name: Atom GetInfo
on:
  workflow_call:
    outputs:
      repo_name:
        description: 'For example, https://github.com/facebook/react, name is react.'
        value: ${{ jobs.compute.outputs.repo_name }}
jobs:
  compute:
    runs-on: ubuntu-latest
    outputs:
      repo_name: ${{ steps.get_repo_name.outputs.repo_name }}
    steps:
      - id: get_repo_name
        run: echo "repo_name=$(echo ${{ github.repository }} | cut -d'/' -f 2-)" >> $GITHUB_OUTPUT
