name: CI
on:
  push:
    branches-ignore:
      - master
  pull_request:
    branches:
      - master
    types:
      - opened
jobs:
  show_info:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.ref }}
      - run: echo ${{ github.repository }}

  test:
    needs: [show_info]
    uses: './.github/workflows/base.test.yml'

  build:
    needs: [test]
    uses: './.github/workflows/base.build.yml'
