name: CI
on:
  push:
    branches-ignore:
      - master
  pull_request:
    branches:
      - master
    types:
      - opened
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - run: echo [repositoryUrl] ${{ github.repositoryUrl }}
      - run: echo [ref] ${{ github.ref }}
      - run: echo [event_name] ${{ github.event_name }}

  test:
    needs: [info]
    uses: './.github/workflows/atom.test.yml'

  build:
    needs: [info]
    uses: './.github/workflows/atom.build.yml'

  publish:
    needs: [build]
    uses: './.github/workflows/atom.publish.yml'
