name: Test-Build-Publish
on:
  push:
  pull_request:
    branches: master
    types: closed
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.ref }}
      - name: Checkout code
        uses: actions/checkout@main
      - name: Install Node.js
        uses: actions/setup-node@v3
      - run: npm i
      - run: npm run test
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/clover.xml
          fail_ci_if_error: true
          verbose: true

  build:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main
      - name: Install Node.js
        uses: actions/setup-node@v3
      - run: npm i
      - run: npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: dist

  publish:
    if: ${{ github.ref == 'refs/heads/master' && github.event.pull_request.merged == true }}
    needs: [test, build]
    runs-on: ubuntu-latest
    steps:
      - run: echo The PR was merged
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          path: dist
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          registry-url: 'https://registry.npmjs.org'
      - run: npm publish ./dist --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
